<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>03</title>
</head>
<body>
    <h1>1.mark</h1>
    <p><b>write</b>n 2010, another research team at the University of Michigan found a 40% decline among students in every definition of empathy among college students, as compared to their</p>
    <li>The list of positive and negative repercussions of increased</li>
    
</body>
</html>
